/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package arbolavl;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author Dren
 */
public class ventana extends javax.swing.JFrame {
    Graphics g;
    public static final int an = 50;
    public static final int diam = 30;
    public static final int r = diam / 2;
    Metodos arbol;
    /**
     * Creates new form ventana
     */
    public ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        agragarB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        agragarB.setText("Agregar");
        agragarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agragarBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(agragarB)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agragarB)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agragarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agragarBActionPerformed
       String s = JOptionPane.showInputDialog("Digite el valor:");
       int i = Integer.valueOf(s);
       int x= Panel.getWidth()/2;
       raiz=Metodos.insertarAVL(raiz,i);
       preOrdenNR(raiz);
       pintarr(g,x/2,20,raiz);
    }//GEN-LAST:event_agragarBActionPerformed

        public void pintarr(Graphics g, int x, int y, Nodo n) {
        if (n == null)
        {}
        else {
            int EXTRA = arbol.completos(n) * (an / 2);
            g.drawOval(x, y, diam, diam);

            if (n.getIzquierdo()!= null)
                g.drawLine(x + r, y + r, x - an - EXTRA + r, y + r + an);
                g.setColor(Color.BLACK);
            if (n.getDerecho() != null) 
                g.drawLine(x + r, y + r, x + an + EXTRA + r, y + r + an);
                g.setColor(Color.BLACK);
                g.fillOval(x, y, diam, diam);
                pintarr(g,x - an - EXTRA ,y + an,n.getIzquierdo());
                pintarr(g,x + an + EXTRA ,y + an,n.getDerecho());
                g.setColor(Color.yellow);
                String dato=""+n.getDato();
            g.drawString(dato, x + 12, y + 18);
        }
    }
    public static void preOrdenNR(Nodo raiz){
        Stack<Nodo> pila = new Stack();
        do{
            if(raiz!=null){
                System.out.print(raiz.getDato()+" ");  
                
                pila.add(raiz);
                raiz=raiz.getIzquierdo();
            }else{
                raiz=pila.pop();
                raiz=raiz.getDerecho();
            }
        }while(!pila.isEmpty() || raiz!=null);
        System.out.println(" ");
        System.out.println("+++++++++++++++++++++++++++++++");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana().setVisible(true);
            }
        });
    }
        Nodo raiz=null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agragarB;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
